version: '3'
services:
  app: 
    image: node
    user: node:node
    working_dir: /app
    container_name: app-courses
    depends_on:
      - database
      - rabbitmq
    ports: 
      - '5000:3000'
    networks:
      - default
    volumes:
      - ./:/app
    command: 'npm run start:dev'

  database:
    image: postgres
    container_name: postgres_db_courses
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRESS_DB: db_courses
    ports:
      - '5432:5432'
    volumes:
      - db_courses:/var/lib/postgresql/data
    networks:
      - default

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - default
      - app-certifications_default

volumes:
  db_courses:
    driver: local
networks:
  default:
    driver: bridge
  app-certifications_default:
    external: true